# Generated by Django 4.0.4 on 2022-05-31 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testpage',
            name='body',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
