# Generated by Django 4.0.4 on 2022-05-31 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0002_testpage_body'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestPage',
        ),
    ]
