# Generated by Django 4.0.4 on 2022-05-31 05:43

from django.db import migrations, models
import django.db.models.deletion
import streams.blocks
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('title', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('footer', wagtail.fields.StreamField([('contents', wagtail.blocks.StructBlock([('title', streams.blocks.CharBlock()), ('content', wagtail.blocks.RichTextBlock(label='Message'))])), ('extlinks', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=250, required=True)), ('links', wagtail.blocks.StreamBlock([('link', wagtail.blocks.StructBlock([('link', wagtail.blocks.RichTextBlock(features=['link'], required=True)), ('visible', wagtail.blocks.BooleanBlock(default=True, required=False))]))]))], icon='link', label='External Links'))], blank=True, null=True, use_json_field=None)),
            ],
            options={
                'verbose_name': 'Footer',
                'verbose_name_plural': 'Footers',
            },
        ),
        migrations.CreateModel(
            name='Sidebar',
            fields=[
                ('title', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('sidebar', wagtail.fields.StreamField([('sidebar', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=250, required=True)), ('links', wagtail.blocks.StreamBlock([('link', wagtail.blocks.StructBlock([('link', wagtail.blocks.RichTextBlock(features=['link'], required=True)), ('visible', wagtail.blocks.BooleanBlock(default=True, required=False))]))]))]))], blank=True, null=True, use_json_field=None)),
            ],
            options={
                'verbose_name': 'Sidebar',
                'verbose_name_plural': 'Sidebars',
            },
        ),
        migrations.CreateModel(
            name='Navbar',
            fields=[
                ('title', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('links', wagtail.fields.StreamField([('navs', wagtail.blocks.StructBlock([('link', wagtail.blocks.RichTextBlock(features=['link'], required=True)), ('visible', wagtail.blocks.BooleanBlock(default=True, required=False))]))], blank=True, null=True, use_json_field=None)),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Navbar',
                'verbose_name_plural': 'Navbars',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('title', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
            },
        ),
    ]
