# Generated by Django 4.0.4 on 2022-05-31 08:20

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0069_log_entry_jsonfield'),
        ('layout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbar',
            name='links',
            field=wagtail.fields.StreamField([('navs', wagtail.blocks.StructBlock([('link', wagtail.blocks.RichTextBlock(features=['link'], required=True)), ('visible', wagtail.blocks.BooleanBlock(default=True, required=False))])), ('dropdown', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=250, required=True)), ('links', wagtail.blocks.StreamBlock([('link', wagtail.blocks.StructBlock([('link', wagtail.blocks.RichTextBlock(features=['link'], required=True)), ('visible', wagtail.blocks.BooleanBlock(default=True, required=False))]))]))], icon='link', label='Dropdown Links'))], blank=True, null=True, use_json_field=None),
        ),
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('banner', modelcluster.fields.ParentalManyToManyField(blank=True, to='layout.banner')),
                ('navbar', modelcluster.fields.ParentalManyToManyField(blank=True, to='layout.navbar')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
